### ISSUE TITLE
Changing window rim color seems to be leading to awful error

### ISSUE THREAD

**Issue by s1ddok** [insidegui/AppearanceMaker#7]
I'm trying to use this app for customizing my app's appearance in order to make it simillar to what Adobe Photoshop has. 

But when I try to change window rim color it leads to an ugly error, which looks like my window rim draws everything beneath it to itself and that's it. It also seems like user has to be able to choose gradients of color, not just a single color, at least that's what how default setting appear.

**Comment by insidegui** [comment]
I didn't have this issue before, but It's probably related to the underlying frameworks rather than something AppearanceMaker does. The app is only exposing a system made by Apple and since the system is private we can't really open radars with them about It 😬

With that said, if you want your window to have a dark rim, try subclassing It and overriding `effectiveAppearance` to return the vibrant dark appearance, that will make the window rim dark.

[Here's a sample](https://gist.github.com/insidegui/24e4ebaeee8a13e101c93bb38faacf23).

![captura de tela 2016-05-14 as 14 24 38](https://cloud.githubusercontent.com/assets/67184/15269753/ba08cf8c-19df-11e6-9898-5ac28f6536e3.png)

**Comment by s1ddok** [comment]
I'm trying to make a dark the thing underneath "Window" title, I thought it is a window rim...

**Comment by insidegui** [comment]
Ah, I see. The rim is actually the border around the window. I'm closing this issue since It's unrelated to the project itself.

**Comment by s1ddok** [comment]
Well, closing the issue is of course up to you, but it won't change the fact that after changing rim's color, title bar goes awfully broken.
